backbone.first_channels:
  chosen: 16
backbone.last_channels:
  chosen: 1984
backbone.layers.1.kernel_size:
  chosen: 3
backbone.layers.1.depth:
  chosen: 1
backbone.layers.1.expand_ratio:
  chosen: 1
backbone.layers.1.out_channels:
  chosen: 24
backbone.layers.2.kernel_size:
  chosen: 3
backbone.layers.2.depth:
  chosen: 3
backbone.layers.2.expand_ratio:
  chosen: 4
backbone.layers.2.out_channels:
  chosen: 32
backbone.layers.3.kernel_size:
  chosen: 3
backbone.layers.3.depth:
  chosen: 3
backbone.layers.3.expand_ratio:
  chosen: 6
backbone.layers.3.out_channels:
  chosen: 40
backbone.layers.4.kernel_size:
  chosen: 3
backbone.layers.4.depth:
  chosen: 4
backbone.layers.4.expand_ratio:
  chosen: 5
backbone.layers.4.out_channels:
  chosen: 72
backbone.layers.5.kernel_size:
  chosen: 3
backbone.layers.5.depth:
  chosen: 4
backbone.layers.5.expand_ratio:
  chosen: 4
backbone.layers.5.out_channels:
  chosen: 128
backbone.layers.6.kernel_size:
  chosen: 5
backbone.layers.6.depth:
  chosen: 6
backbone.layers.6.expand_ratio:
  chosen: 6
backbone.layers.6.out_channels:
  chosen: 216
backbone.layers.7.kernel_size:
  chosen: 3
backbone.layers.7.depth:
  chosen: 1
backbone.layers.7.expand_ratio:
  chosen: 6
backbone.layers.7.out_channels:
  chosen: 224
input_shape:
  chosen:
  - 288
  - 288
