Collections:
  - Name: YOLOX
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - Cosine Annealing Lr Updater
      Training Resources: 8x A100 GPUs
      Architecture:
        - CSPDarkNet
        - PAFPN
    Paper:
      URL: https://arxiv.org/abs/2107.08430
      Title: 'YOLOX: Exceeding YOLO Series in 2021'
    README: configs/yolox/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.1.0/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.1.0


Models:
  - Name: yolox_tiny_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_tiny_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 2.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 32.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_tiny_8xb8-300e_coco/yolox_tiny_8xb8-300e_coco_20220919_090908-0e40a6fc.pth
  - Name: yolox_s_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_s_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 5.6
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.8
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_s_8xb8-300e_coco/yolox_s_8xb8-300e_coco_20220917_030738-d7e60cb2.pth
