Collections:
  - Name: YOLOX
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - Cosine Annealing Lr Updater
      Training Resources: 8x A100 GPUs
      Architecture:
        - CSPDarkNet
        - PAFPN
    Paper:
      URL: https://arxiv.org/abs/2107.08430
      Title: 'YOLOX: Exceeding YOLO Series in 2021'
    README: configs/yolox/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.1.0/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.1.0


Models:
  - Name: yolox_tiny_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_tiny_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 2.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 32.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_tiny_8xb8-300e_coco/yolox_tiny_8xb8-300e_coco_20220919_090908-0e40a6fc.pth
  - Name: yolox_s_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_s_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 2.9
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_s_fast_8xb8-300e_coco/yolox_s_fast_8xb8-300e_coco_20230213_142600-2b224d8b.pth
  - Name: yolox_m_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_m_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 4.9
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.9
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_m_fast_8xb8-300e_coco/yolox_m_fast_8xb8-300e_coco_20230213_160218-a71a6b25.pth
  - Name: yolox_l_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_l_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 8.0
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 50.1
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_l_fast_8xb8-300e_coco/yolox_l_fast_8xb8-300e_coco_20230213_160715-c731eb1c.pth
  - Name: yolox_x_fast_8xb8-300e_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_x_fast_8xb8-300e_coco.py
    Metadata:
      Training Memory (GB): 9.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.4
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_x_fast_8xb8-300e_coco/yolox_x_fast_8xb8-300e_coco_20230215_133950-1d509fab.pth
  - Name: yolox_tiny_fast_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_tiny_fast_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 4.9
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 34.3
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_tiny_fast_8xb32-300e-rtmdet-hyp_coco/yolox_tiny_fast_8xb32-300e-rtmdet-hyp_coco_20230210_143637-4c338102.pth
  - Name: yolox_s_fast_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_s_fast_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 9.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.9
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_s_fast_8xb32-300e-rtmdet-hyp_coco/yolox_s_fast_8xb32-300e-rtmdet-hyp_coco_20230210_134645-3a8dfbd7.pth
  - Name: yolox_m_fast_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: configs/yolox/yolox_m_fast_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 17.6
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 47.5
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/yolox_m_fast_8xb32-300e-rtmdet-hyp_coco/yolox_m_fast_8xb32-300e-rtmdet-hyp_coco_20230210_144328-e657e182.pth
  - Name: yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 5.3
      Epochs: 300
    Results:
      - Task: Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 52.8
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/pose/yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco/yolox-pose_tiny_8xb32-300e-rtmdet-hyp_coco_20230427_080351-2117af67.pth
  - Name: yolox-pose_s_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: yolox-pose_s_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 10.7
      Epochs: 300
    Results:
      - Task: Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 63.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/pose/yolox-pose_s_8xb32-300e-rtmdet-hyp_coco/yolox-pose_s_8xb32-300e-rtmdet-hyp_coco_20230427_005150-e87d843a.pth
  - Name: yolox-pose_m_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: yolox-pose_m_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 19.2
      Epochs: 300
    Results:
      - Task: Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 69.3
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/pose/yolox-pose_m_8xb32-300e-rtmdet-hyp_coco/yolox-pose_m_8xb32-300e-rtmdet-hyp_coco_20230427_094024-bbeacc1c.pth
  - Name: yolox-pose_l_8xb32-300e-rtmdet-hyp_coco
    In Collection: YOLOX
    Config: yolox-pose_l_8xb32-300e-rtmdet-hyp_coco.py
    Metadata:
      Training Memory (GB): 30.3
      Epochs: 300
    Results:
      - Task: Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 71.1
    Weights: https://download.openmmlab.com/mmyolo/v0/yolox/pose/yolox-pose_l_8xb32-300e-rtmdet-hyp_coco/yolox-pose_l_8xb32-300e-rtmdet-hyp_coco_20230427_041140-82d65ac8.pth
